name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: infra/terraform
  GHCR_REGISTRY: ghcr.io
  PROJECT_NAME: kafka-enterprise-orders

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # ---------------- Checkout repo ----------------
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------------- Docker Build & Push ----------------
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push order-producer image
        uses: docker/build-push-action@v6
        with:
          context: ./producer
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/ermekerkimbaev/kafka-enterprise-orders/order-producer:latest

      # ---------------- Terraform Setup ----------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ---------------- Terraform Init ----------------
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -backend-config="bucket=kafka-enterprise-orders-terraform-state" \
                             -backend-config="key=kafka-enterprise-orders/terraform.tfstate" \
                             -backend-config="region=${{ env.AWS_REGION }}" \
                             -backend-config="dynamodb_table=terraform-locks"

      # ---------------- Terraform Plan ----------------
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan

      # ---------------- Terraform Apply ----------------
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan

